### PR TITLE
Added Contributor Code of Conduct

### PR DESCRIPTION
**Pull request by lwaldron**

### CODE REVIEW

**Comment by seandavi** [comment]
Nicely done....

**Comment by ttriche** [comment]
"Unprofessional" is a loaded word.  Professionals can be racist, sexist, poisonous human beings. Some of the most lucrative professions in our society appear to actively encourage dishonesty (http://www.nature.com/nature/journal/v516/n7529/full/nature13977.html). 

Hookers and hit men are professionals. Most artists & actors, as well as many productive scholars, are amateurs. Are the contributions of hit men inherently more valuable than volunteer thespians?

If you want to be inclusive, don't condition participation on whether someone pretends that this is their day job. Condition it on whether they are attempting to move humanity forward, and whether they treat other human beings with respect. 

Just my $0.02...

--t

**Comment by lwaldron** [comment]
How about "disrespectful" instead of "unprofessional" ? Respectfulness is
really the point of the rest of that paragraph.

**Comment by seandavi** [comment]
I think disrespectful is a nice substitution.

Sean

**Comment by ttriche** [comment]
Absolutely 100% agreed.  Respect for others should not be conflated with a
desire for money.  :-)



Statistics is the grammar of science.
Karl Pearson <http://en.wikipedia.org/wiki/The_Grammar_of_Science>

**Pull request merged**
